# _config.yml

# Configuraci贸n general
title: "Seminarios de la 324"
description: "Todos los viernes a las 14:00 hs en el aula 324."
lang: es
author: "Oficina 324 - FAMAF"
email: nicolasvazquez.vonbibow@unc.edu.ar

# Tema
theme: minima

# Configuraci贸n de posts
collections:
  posts:
    output: true

# Plugins
plugins:
  - jekyll-feed

# Configuraci贸n opcional para URL
permalink: /:year/:month/:day/:title/

################################################################
# 隆AADIR ESTA SECCIN! 
################################################################
# Configuraci贸n de GitHub Pages
# URL principal del sitio
url: "https://nicolasvazquez95.github.io"
# Subdirectorio del sitio (el nombre de tu repositorio)
baseurl: "/seminarios324"
################################################################